title: Breadcrumb.js
description: All URI paths are automatically displayed in an element.
theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/tobiasroeder/Breadcrumb.js/zipball/master
  tar_url: https://github.com/tobiasroeder/Breadcrumb.js/tarball/master
